[package]
name = "baudowl"
version = "1.0.0"
edition = "2021"
authors = ["IoTSRG Team"]
description = "The Ultimate Serial Port Detective"
license = "MIT"
repository = "https://github.com/iotsrg/baudowl"

[[bin]]
name = "baudowl"
path = "src/main.rs"

[dependencies]
serialport = "4.2"
clap = { version = "4.0", features = ["derive"] }
ctrlc = "3.2"
colored = "2.0"
